services:
  app:
    build: 
      context: .
      dockerfile: ./apps/web/Dockerfile
    image: ishowfinance
    container_name: ishowfinance
    restart: unless-stopped
    ports:
      - '7600:3000'