services:
  web:
    build: 
      context: .
      dockerfile: ./apps/web/Dockerfile
    image: ishowfinance
    container_name: ishowfinance
    restart: unless-stopped
    ports:
      - '7600:3000'

  api:
    build: 
      context: .
      dockerfile: ./apps/api/Dockerfile
    image: ishowfinance
    container_name: ishowfinance-api
    restart: unless-stopped
    ports:
      - '7700:3001'